//! The conformance wire shapes, defined once: the results files the
//! adapters write and the runner validates (see the runner's doc header for
//! the transport invariants), and the suite lockfile `just
//! update-conformance-lock` writes and the runner reads back.
//!
//! Data types only, no I/O: the composed driver compiles this crate to
//! `wasm32-wasip2`. The JS adapters (`conformance/adapters/jco`) produce
//! the same shapes by convention; this crate is the Rust side's single
//! definition of it.

use serde::{Deserialize, Serialize};

/// One case's outcome, as the `outcome` field spells it.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Outcome {
    Pass,
    Fail,
    Skipped,
    /// Any other string in a results file. Validation flags it; rendering
    /// treats it as "no result". Never written by the Rust adapters.
    #[serde(other)]
    Unknown,
}

/// One case result.
#[derive(Debug, Serialize, Deserialize)]
pub struct CaseResult {
    pub name: String,
    #[serde(default)]
    pub features: Vec<String>,
    pub outcome: Outcome,
    #[serde(default)]
    pub detail: String,
}

/// A results file: one (target, suite) run.
#[derive(Debug, Serialize, Deserialize)]
pub struct ResultsFile {
    pub target: String,
    pub suite: String,
    #[serde(rename = "missing-features")]
    pub missing_features: Vec<String>,
    pub results: Vec<CaseResult>,
}

/// One lockfile case: its stable name plus the feature tags it exercises.
#[derive(Debug, Deserialize)]
pub struct LockCase {
    pub name: String,
    #[serde(default)]
    pub features: Vec<String>,
}

#[cfg(feature = "lock")]
mod lock {
    use super::LockCase;

    #[derive(serde::Deserialize)]
    struct LockFile {
        cases: Vec<LockCase>,
    }

    /// Parse a lockfile (TOML: a `cases` array of `{ name, features? }`
    /// inline tables, as [`render_lock`] writes it).
    pub fn parse_lock(text: &str) -> Result<Vec<LockCase>, toml::de::Error> {
        Ok(toml::from_str::<LockFile>(text)?.cases)
    }

    /// Render a lockfile: TOML, one inline table per case (name, then any
    /// feature tags), in suite order — one line per case, so suite changes
    /// diff case by case.
    pub fn render_lock(cases: &[LockCase]) -> String {
        let mut lock = String::from(
            "# The conformance suite's cases, one per line (name, plus the feature tags\n\
             # it exercises), in suite order. Generated by `just update-conformance-lock`;\n\
             # do not edit. The runner validates every results file against this\n\
             # inventory, so case changes must land here intentionally.\n\
             cases = [\n",
        );
        for case in cases {
            lock.push_str(&format!(
                "    {{ name = {}",
                toml::Value::from(case.name.as_str())
            ));
            if !case.features.is_empty() {
                lock.push_str(&format!(
                    ", features = {}",
                    toml::Value::from(case.features.clone())
                ));
            }
            lock.push_str(" },\n");
        }
        lock.push_str("]\n");
        lock
    }

    #[cfg(test)]
    mod tests {
        use super::*;

        /// The lockfile format round-trips, including a name TOML must
        /// escape — the writer renders TOML strings, not Rust `Debug`.
        #[test]
        fn lock_round_trips_with_escaping() {
            let cases = vec![
                LockCase {
                    name: "alg/src/tc1/whole".into(),
                    features: vec![],
                },
                LockCase {
                    name: "quote\"and\\slash".into(),
                    features: vec!["chacha20-poly1305".into()],
                },
            ];
            let rendered = render_lock(&cases);
            let parsed = parse_lock(&rendered).unwrap();
            assert_eq!(parsed.len(), 2);
            assert_eq!(parsed[0].name, cases[0].name);
            assert_eq!(parsed[1].name, cases[1].name);
            assert_eq!(parsed[1].features, cases[1].features);
        }

        /// The rendered shape is the one-line-per-case inline-table format
        /// the checked-in lockfiles use.
        #[test]
        fn lock_renders_one_inline_table_per_case() {
            let rendered = render_lock(&[LockCase {
                name: "probe/check".into(),
                features: vec!["f".into()],
            }]);
            assert!(
                rendered.contains("    { name = \"probe/check\", features = [\"f\"] },\n"),
                "{rendered}"
            );
        }
    }
}

#[cfg(feature = "lock")]
pub use lock::{parse_lock, render_lock};

#[cfg(test)]
mod tests {
    use super::*;

    /// The runner must accept whatever outcome string an adapter writes:
    /// the three known ones map to their cases, anything else to
    /// [`Outcome::Unknown`] (flagged by validation, rendered as absent).
    #[test]
    fn outcome_accepts_unknown_strings() {
        let outcomes: Vec<Outcome> =
            serde_json::from_str(r#"["pass", "fail", "skipped", "mystery"]"#).unwrap();
        assert_eq!(
            outcomes,
            [
                Outcome::Pass,
                Outcome::Fail,
                Outcome::Skipped,
                Outcome::Unknown
            ]
        );
        assert_eq!(serde_json::to_string(&Outcome::Pass).unwrap(), "\"pass\"");
    }
}
