// The vendored WPT groups and the subset definition, shared by every
// environment that runs them: `runner.js` and `parity-runner.js`
// (componentize-js guests, static imports), and the parity legs' shared
// baseline loop in `parity-helpers.js` (Node and the browser parity page,
// dynamic imports). This module is
// dependency-free — it names each group's suite module instead of importing
// it — so its specifier resolves identically under componentize-js's
// base-directory resolution and ordinary ESM.
//
// Each entry is `{ name, module, start, inSubset }`:
//
//   - `name` keys the group everywhere results are recorded: the census in
//     `expected.js`, the loss ratchet in `parity/losses.js`, and the parity
//     comparator's records.
//   - `module` is the suite module's filename under `build/` (generated by
//     `component.sh suites`); the consumer resolves and imports it.
//   - `start(ns)` registers the group's tests, given that module's
//     namespace. It runs with `harness.js`'s globals installed
//     (`promise_test` and friends).
//   - `inSubset(name)` classifies a test by its WPT name: *in-subset* tests
//     — those whose parameters the webcrypto-componentize library documents
//     as served — must pass under the gating runner; the rest are expected
//     to fail with the library's documented fail-closed errors. These
//     classifiers are the machine-readable definition of "the portion of
//     WPT this library implements"; their doc comments enumerate each
//     group's boundary.

// --- the subset definition, one classifier per group ---------------------------

/**
 * sign_verify/hmac: the served hashes (SHA-1 through the package's
 * `hmac-sha1` interface, and the SHA-2 family); the wrong-algorithm tests
 * need ECDSA generation (class D).
 */
function hmacInSubset(name) {
  if (name === "setup") {
    return true;
  }
  return /SHA-(1|256|384|512)\b/.test(name) && !/wrong algorithm|generate wrong key/.test(name);
}

/**
 * encrypt_decrypt/aes_gcm (both the 96-bit- and 256-bit-iv groups; the
 * per-call `iv` parameter carries any length): 128- and 256-bit keys at
 * every legal tag length (per-call `tag-size` carries them all), plus the
 * illegal-tag-length rejections and the mismatched-key tests (their
 * AES-CBC fixture is served); AES-192 is declined package-wide.
 */
function gcmInSubset(name) {
  if (name === "setup") {
    return true;
  }
  return /(128|256)-bit key/.test(name);
}

/**
 * encrypt_decrypt/{aes_cbc,aes_ctr}: 128- and 256-bit keys; AES-192 is
 * declined package-wide, and the mismatched-key test needs the *other*
 * unauthenticated mode's fixture to import (it does — both are served —
 * so it is in).
 * @param {string} name
 */
function cipherInSubset(name) {
  return name === "setup" || /(128|256)-bit key/.test(name);
}

/**
 * encrypt_decrypt/chacha20_poly1305: the whole group — the fixed-vector
 * encryptions and decryptions over "raw-secret" imports, the generated-key
 * round trips, the tamper rejections, and the 12-byte-nonce rule (the
 * WIT's `invalid-nonce` renders the expected `OperationError`).
 */
function chachaEncryptDecryptInSubset() {
  return true;
}

/**
 * import_export/symmetric_importKey (ChaCha20-Poly1305): the "raw-secret"
 * and "jwk" rows (the proposal's oct form, which the package's
 * `chacha20-poly1305.import-key-jwk` serves) are in whole, as are the
 * empty-usages rows for every format (usages are validated before the
 * format is considered).
 * @param {string} name
 */
function chachaImportKeyInSubset(name) {
  if (name.startsWith("Empty Usages:")) {
    return true;
  }
  return name.includes("(raw-secret, ") || name.includes("(jwk, ");
}

/**
 * generateKey/successes (ChaCha20-Poly1305): the whole group — the
 * extractable rows export raw-secret and the oct JWK, both
 * served.
 */
function chachaGenerateKeyInSubset() {
  return true;
}

/**
 * generateKey/failures, in both invocations: the served-algorithms sweep
 * (HMAC, the AES family, Ed25519, X25519) and the ChaCha20-Poly1305 one.
 * The whole group is in-subset — the suite asserts the spec's error
 * ordering (algorithm normalization, nested hash included; then usage
 * membership; then algorithm properties; then the empty-usage check),
 * which this library implements for every served algorithm. The AES-192
 * rows are in too: their expected errors are usage and length checks that
 * precede the mint, so they never reach the package-wide AES-192 decline.
 */
function generateKeyFailuresInSubset() {
  return true;
}

/**
 * import_export/symmetric_importKey: the "raw" and "jwk" formats;
 * HMAC-SHA-256 at any key size, the AES family at 128/256 bits.
 * Empty-usages tests are in for any parameters (usages are validated
 * before key material either way).
 */
function importKeyInSubset(name) {
  if (!name.includes("(raw, ") && !name.includes("(jwk, ")) {
    return false;
  }
  if (name.startsWith("Empty Usages:")) {
    return true;
  }
  if (/\{hash: SHA-(1|256|384|512), name: HMAC\}/.test(name)) {
    return true;
  }
  if (/\{name: AES-(GCM|CBC|CTR)\}/.test(name)) {
    return / (128|256) bits /.test(name);
  }
  return false;
}

/**
 * generateKey/successes: HMAC-SHA-256 (default or explicit length) and
 * AES-GCM at 256 bits, extractable or not (extractable cases export raw
 * and JWK), at every legal usage combination (wrap/unwrap usages are key
 * metadata). Algorithm-name case variants are in (names are
 * case-insensitive).
 */
function generateKeyInSubset(name) {
  if (/name: hmac/i.test(name)) {
    return /hash: SHA-(1|256|384|512)\b/.test(name);
  }
  if (/name: aes-(gcm|cbc|ctr)/i.test(name)) {
    return /length: (128|256)/.test(name);
  }
  return false;
}

/**
 * sign_verify/ecdsa: every test needs ECDSA signing or a generated pair —
 * `ecdsa-sign` is class D, withheld by the in-guest provider this shim
 * composes with (see the shim header) — so the subset stays empty and the
 * group meters that gap. The verify path's behavioral assertions live in
 * the conformance suites.
 */
function classDGatedInSubset() {
  return false;
}

/**
 * sign_verify/{rsa_pss,rsa_pkcs}: every subtest — the verification rows
 * included — runs `rsa.js`'s importVectorKeys, which imports the vector's
 * private pkcs8 fixture alongside its public one, and RSA private-key
 * import is unserved (the package's RSA signature surface is verification-only —
 * see the shim header). Every subtest therefore fails at its import step,
 * registering under the synthetic "importVectorKeys step:" name, so the
 * subset stays empty and the groups meter the unserved private side, like
 * sign_verify/ecdsa above. The verify path's behavioral assertions
 * (Wycheproof, wrong salt lengths, strict PKCS#1 v1.5 encoding) live in
 * the conformance suites. The one passing test is the assertion-free
 * "setup", pinned as `outPassed`.
 */
function rsaSignVerifyInSubset() {
  return false;
}

/**
 * encrypt_decrypt/rsa_oaep: every subtest — the encryption rows included —
 * runs importVectorKeys, which imports both halves of the vector's
 * RSA-OAEP pair, and the whole family is unserved by composition: the
 * in-guest provider this shim composes with withholds both minting
 * interfaces (`rsa-oaep-decrypt` is class D, and OAEP encryption has no
 * secret-free half — see the shim header), so the world cannot import
 * either. Every subtest therefore fails at its import step, registering
 * under the synthetic "importVectorKeys step:" name, so the subset stays
 * empty and the group meters the unserved family, like sign_verify/ecdsa
 * above. The decrypt path's behavioral assertions (Wycheproof) live in
 * the conformance suites. The one passing test is the assertion-free
 * "setup", pinned as `outPassed`.
 */
function rsaOaepInSubset() {
  return false;
}

/**
 * import_export/rsa_importKey: the public forms of the served RSA
 * signature algorithms are in — spki and public JWKs (`object(kty, n,
 * e)`) for RSASSA-PKCS1-v1_5 and RSA-PSS over SHA-256/384/512, at every
 * modulus size the file exercises (1024/2048/4096, all inside the `rsa`
 * family contract's 1024–16384-bit window) and every public usage
 * sweep (`[verify]`, `[]`, and the repeated form). Out: the SHA-1 rows
 * (the `rsa-variant` pairing the package declines — the shim header's
 * narrowed-uniformly entry), the RSA-OAEP rows (unserved algorithm), and
 * the private forms — pkcs8 rows, JWKs carrying `d` (`object(kty, n, e,
 * d, …)`), and the Empty Usages rows, which are registered for the
 * private formats only (their spec SyntaxError follows a private-key
 * parse this shim declines first; their names carry the whole fixture
 * record, `object(spki, pkcs8, jwk)`, which is why the format checks
 * below anchor on each public form's data shape).
 * @param {string} name
 */
function rsaImportInSubset(name) {
  if (!name.startsWith("Good parameters: ")) {
    return false;
  }
  if (!/name: (RSA-PSS|RSASSA-PKCS1-v1_5)\}/.test(name)) {
    return false;
  }
  if (name.includes("{hash: SHA-1,")) {
    return false;
  }
  return name.includes("(spki, buffer(") || name.includes("(jwk, object(kty, n, e),");
}

/**
 * derive_bits_keys/cfrg_curves_bits (X25519): served in whole — the
 * "mismatched algorithms" fixture is an imported ECDH public key, which
 * the library serves.
 */
function cfrgBitsInSubset() {
  return true;
}

/**
 * derive_bits_keys/{ecdh_bits,ecdh_keys}: the P-256 and P-384 rows are
 * served — the agreements (with ecdh_bits' truncated and non-multiple-of-8
 * lengths), the mixed-case algorithm names, and the TypeError/
 * InvalidAccessError rejections, whose fixtures all import (the
 * mismatched-curves peer is the other served curve; the secret-key
 * fixtures are AES-CBC and HMAC). Out: the P-521 rows (declared by the
 * WIT, served by nothing — except that its missing-public and
 * non-CryptoKey rows expect a `TypeError` thrown before any P-521 key is
 * touched, so they pass, which the census pins as `outPassed`), and every
 * curve's "not an ECDSA public key" row, whose fixture is a generated
 * ECDSA pair (class D, see the shim header).
 * @param {string} name
 */
function ecdhDeriveInSubset(name) {
  if (name === "setup - define tests") {
    return true;
  }
  if (name.startsWith("P-521")) {
    return false;
  }
  return !name.includes("not an ECDSA public key");
}

/**
 * import_export/okp_importKey (Ed25519): every served form — raw and spki
 * public, private PKCS#8 and OKP JWKs (public and private).
 */
function okpEd25519ImportInSubset() {
  return true;
}

/**
 * import_export/okp_importKey_failures (Ed25519): every form's rejections
 * are served.
 */
function okpEd25519FailuresInSubset() {
  return true;
}

/**
 * derive_bits_keys/{hkdf,pbkdf2}: the served subset is SHA-256/384/512
 * derivations over importable base secrets, with derived-key targets the
 * WIT's `derive-key` mints span (AES-GCM 256, HMAC-SHA-256).
 *
 * Excluded: unserved derived-key targets. The SHA-1 rows are served
 * (the `hkdf-sha1`/`pbkdf2-sha1`
 * interfaces), the wrong-key rows' fixture (a generated ECDH private
 * key) is served, and so is the empty HKDF base key (empty KDF secrets
 * are accepted package-wide — see `wit/README.md`, "Empty KDF secrets are
 * accepted").
 *
 * The exclusions are whole-row, so the census pins a large `outPassed`
 * for these groups: an unserved-target row's bad-hash and missing-usage
 * subtests often expect the same `DOMException` name the unserved-target
 * refusal carries, and pass for that wrong reason. Claiming a
 * coincidence would let it silently break when the target is served, so
 * they stay out-of-subset, visible in the pinned census.
 * @param {string} name
 */
function kdfDeriveInSubset(name) {
  if (name === "setup - define tests") {
    return true;
  }
  if (name.startsWith("Derived key of type")) {
    const served =
      /^Derived key of type name: AES-(GCM|CBC|CTR|KW) length: (128|256)/.test(name) ||
      /^Derived key of type name: HMAC hash: SHA-(1|256|384|512)\b/.test(name);
    if (!served) {
      return false;
    }
  }
  if (/bad hash name|missing deriveBits usage|missing deriveKey usage/.test(name)) {
    return true;
  }
  return true;
}

/**
 * derive_bits_keys/derived_bits_length: the `length` parameter's edge
 * semantics — explicit sizes, zero (an empty output), sub-byte lengths
 * (the KDFs reject, the agreements truncate and mask), and null/
 * undefined/omitted (the KDFs reject, an agreement yields its natural
 * output) — for the served HKDF, PBKDF2, X25519, and ECDH rows: the
 * whole group.
 */
function derivedBitsLengthInSubset() {
  return true;
}

/**
 * import_export/ec_importKey: the ECDSA P-256/P-384 public forms are
 * served — raw and spki uncompressed points and public EC JWKs — and
 * every ECDH P-256/P-384 form: those public forms plus the private
 * pkcs8 and JWK-with-`d` forms (ECDH private import is served, unlike
 * ECDSA's class-D-blocked private forms; the "ECDH any JWK alg" rows
 * ride the served JWK forms — `alg` is ignored for the ECDH family).
 * Out: the
 * compressed-point rows (an optional feature: `assert_implements_optional`
 * is a failure in this two-status harness, and whether the WIT spki
 * import accepts compression is implementation-defined — the composed
 * provider happens to, which the census pins as `outPassed`), ECDSA's
 * private forms (pkcs8 and JWKs carrying `d` — class D, see the shim
 * header), and P-521 (declared by the WIT and served by nothing).
 * @param {string} name
 */
function ecImportInSubset(name) {
  if (name.includes("P-521") || name.includes("compressed")) {
    return false;
  }
  if (name.includes("name: ECDH")) {
    return true;
  }
  if (!name.includes("name: ECDSA")) {
    return false;
  }
  return !name.includes("(pkcs8") && !name.includes(", d)");
}

/**
 * import_export/ec_importKey_failures (ECDSA): the public-form rejections
 * are served — for P-521 only the usage rejections, whose check precedes
 * the curve's — plus the missing-algorithm-name rows, whose `TypeError`
 * precedes every format and curve consideration. The private forms stay
 * out (class D).
 * @param {string} name
 */
function ecImportFailuresInSubset(name) {
  if (name.startsWith("Missing algorithm name")) {
    return true;
  }
  if (name.includes("(pkcs8") || name.includes("jwk(private)")) {
    return false;
  }
  return name.startsWith("Bad usages") || !name.includes("P-521");
}

/** getRandomValues: the whole group is served. */
function getRandomValuesInSubset() {
  return true;
}

/** randomUUID: the whole group is served. */
function randomUuidInSubset() {
  return true;
}

/**
 * normalize-algorithm-name: ASCII-case-insensitive name matching, probed
 * with Kelvin-sign lookalikes; the whole group is served.
 */
function normalizeAlgorithmNameInSubset() {
  return true;
}

/** crypto_key_cached_slots: the whole group is served. */
function cachedSlotsInSubset() {
  return true;
}

/**
 * digest/digest: the whole group — the SHA-2 family, the bad-algorithm-name
 * rejections, the missing-name `TypeError`s, and the SHA-1 rows, which the
 * shim serves through the package's `sha1-checked` interface (mitigating
 * posture: byte-identical to the platform on every honest input, which is
 * all WPT hashes).
 */
function digestInSubset() {
  return true;
}

/**
 * import_export/okp_importKey (X25519): every served form — raw and spki
 * public, private PKCS#8 and OKP JWKs (public and private), extractable
 * or not (the gated private exports are served).
 */
function okpImportInSubset() {
  return true;
}

/**
 * import_export/okp_importKey_failures (X25519): every form's rejections
 * are served.
 */
function okpImportFailuresInSubset() {
  return true;
}

/**
 * wrapKey_unwrapKey: every combination whose wrapping algorithm and
 * wrapped-key family the library serves — the symmetric families (HMAC,
 * AES-GCM/CBC/CTR/KW, ChaCha20-Poly1305) plus Ed25519, X25519, and ECDH
 * *private* keys, under the AES and ChaCha wrappers. Out of the subset:
 * the RSA-OAEP wrapper (unserved algorithm), the RSA and ECDSA wrappee
 * rows (unserved family; class D), and every public-key wrap
 * (the WIT's public-key resources mint no wrap-input; see the library
 * header's deviations list).
 * @param {string} name
 */
function wrapKeyInSubset(name) {
  if (name === "setup") {
    return true;
  }
  if (/RSA|ECDSA/.test(name)) {
    return false;
  }
  return !/public key/.test(name);
}

// --- the group table --------------------------------------------------------------

export const GROUPS = [
  {
    name: "sign_verify/hmac",
    module: "group-hmac.js",
    start: (ns) => ns.run_test(),
    inSubset: hmacInSubset,
  },
  {
    name: "encrypt_decrypt/aes_gcm (96-bit iv)",
    module: "group-aes-gcm.js",
    start: (ns) => ns.run_test(),
    inSubset: gcmInSubset,
  },
  {
    name: "encrypt_decrypt/aes_gcm (256-bit iv)",
    module: "group-aes-gcm-256-iv.js",
    start: (ns) => ns.run_test(),
    inSubset: gcmInSubset,
  },
  {
    name: "encrypt_decrypt/aes_cbc",
    module: "group-aes-cbc.js",
    start: (ns) => ns.run_test(),
    inSubset: cipherInSubset,
  },
  {
    name: "encrypt_decrypt/aes_ctr",
    module: "group-aes-ctr.js",
    start: (ns) => ns.run_test(),
    inSubset: cipherInSubset,
  },
  {
    name: "encrypt_decrypt/chacha20_poly1305",
    module: "group-chacha20-poly1305.js",
    start: (ns) => ns.run_chacha20_poly1305_tests(),
    inSubset: chachaEncryptDecryptInSubset,
  },
  {
    name: "wrapKey_unwrapKey/wrapKey_unwrapKey",
    module: "group-wrap-key.js",
    start: (ns) => ns.run_wrap_tests(),
    inSubset: wrapKeyInSubset,
  },
  {
    name: "import_export/symmetric_importKey (HMAC, AES-GCM)",
    module: "group-import-key.js",
    start: (ns) => {
      ns.runTests("HMAC");
      ns.runTests("AES-GCM");
    },
    inSubset: importKeyInSubset,
  },
  {
    name: "import_export/symmetric_importKey (ChaCha20-Poly1305)",
    module: "group-import-key.js",
    start: (ns) => ns.runTests("ChaCha20-Poly1305"),
    inSubset: chachaImportKeyInSubset,
  },
  {
    name: "generateKey/successes (HMAC, AES-GCM)",
    module: "group-generate-key.js",
    start: (ns) => ns.run_test(["HMAC", "AES-GCM"]),
    inSubset: generateKeyInSubset,
  },
  {
    name: "generateKey/failures (HMAC, AES, Ed25519, X25519)",
    module: "group-generate-key-failures.js",
    start: (ns) => ns.run_test(["HMAC", "AES-GCM", "AES-CBC", "AES-CTR", "Ed25519", "X25519"]),
    inSubset: generateKeyFailuresInSubset,
  },
  {
    name: "generateKey/successes (ChaCha20-Poly1305)",
    module: "group-generate-key.js",
    start: (ns) => ns.run_test(["ChaCha20-Poly1305"]),
    inSubset: chachaGenerateKeyInSubset,
  },
  {
    name: "generateKey/failures (ChaCha20-Poly1305)",
    module: "group-generate-key-failures.js",
    start: (ns) => ns.run_test(["ChaCha20-Poly1305"]),
    inSubset: generateKeyFailuresInSubset,
  },
  {
    name: "derive_bits_keys/cfrg_curves_bits (X25519)",
    module: "group-cfrg-bits.js",
    start: (ns) => promise_test(ns.define_tests_25519, "setup - define tests"),
    inSubset: cfrgBitsInSubset,
  },
  {
    name: "derive_bits_keys/cfrg_curves_keys (X25519)",
    module: "group-cfrg-keys.js",
    start: (ns) => promise_test(ns.define_tests_25519, "setup - define tests"),
    inSubset: cfrgBitsInSubset,
  },
  {
    name: "derive_bits_keys/ecdh_bits",
    module: "group-ecdh-bits.js",
    start: (ns) => promise_test(ns.define_tests, "setup - define tests"),
    inSubset: ecdhDeriveInSubset,
  },
  {
    name: "derive_bits_keys/ecdh_keys",
    module: "group-ecdh-keys.js",
    start: (ns) => promise_test(ns.define_tests, "setup - define tests"),
    inSubset: ecdhDeriveInSubset,
  },
  {
    name: "import_export/okp_importKey (X25519)",
    module: "group-okp-import-key.js",
    start: (ns) => ns.runTests("X25519"),
    inSubset: okpImportInSubset,
  },
  {
    name: "import_export/okp_importKey_failures (X25519)",
    module: "group-okp-import-key-failures.js",
    start: (ns) => ns.run_test(["X25519"]),
    inSubset: okpImportFailuresInSubset,
  },
  {
    name: "generateKey/successes (X25519)",
    module: "group-generate-key.js",
    start: (ns) => ns.run_test(["X25519"]),
    inSubset: () => true,
  },
  {
    name: "derive_bits_keys/hkdf",
    module: "group-hkdf-derive.js",
    start: (ns) => promise_test(ns.define_tests, "setup - define tests"),
    inSubset: kdfDeriveInSubset,
  },
  {
    name: "derive_bits_keys/pbkdf2",
    module: "group-pbkdf2-derive.js",
    start: (ns) => promise_test(ns.define_tests, "setup - define tests"),
    inSubset: kdfDeriveInSubset,
  },
  {
    name: "derive_bits_keys/derived_bits_length",
    module: "group-derived-bits-length.js",
    start: (ns) => promise_test(ns.define_tests, "setup - define tests"),
    inSubset: derivedBitsLengthInSubset,
  },
  {
    name: "digest/digest",
    module: "group-digest.js",
    start: (ns) => ns.run_digest_tests(),
    inSubset: digestInSubset,
  },
  {
    name: "sign_verify/eddsa (Ed25519)",
    module: "group-eddsa.js",
    start: (ns) => ns.run_test("Ed25519"),
    inSubset: () => true,
  },
  {
    name: "sign_verify/eddsa_small_order_points",
    module: "group-eddsa-small-order.js",
    start: (ns) => ns.run_test(),
    inSubset: () => true,
  },
  {
    name: "sign_verify/ecdsa",
    module: "group-ecdsa.js",
    start: (ns) => ns.run_test(),
    inSubset: classDGatedInSubset,
  },
  {
    name: "sign_verify/rsa_pss",
    module: "group-rsa-pss.js",
    start: (ns) => ns.run_test(),
    inSubset: rsaSignVerifyInSubset,
  },
  {
    name: "sign_verify/rsa_pkcs",
    module: "group-rsa-pkcs.js",
    start: (ns) => ns.run_test(),
    inSubset: rsaSignVerifyInSubset,
  },
  {
    name: "encrypt_decrypt/rsa_oaep",
    module: "group-rsa-oaep.js",
    start: (ns) => ns.run_test(),
    inSubset: rsaOaepInSubset,
  },
  {
    name: "import_export/okp_importKey (Ed25519)",
    module: "group-okp-import-key.js",
    start: (ns) => ns.runTests("Ed25519"),
    inSubset: okpEd25519ImportInSubset,
  },
  {
    name: "import_export/okp_importKey_failures (Ed25519)",
    module: "group-okp-import-key-failures.js",
    start: (ns) => ns.run_test(["Ed25519"]),
    inSubset: okpEd25519FailuresInSubset,
  },
  {
    name: "generateKey/successes (Ed25519)",
    module: "group-generate-key.js",
    start: (ns) => ns.run_test(["Ed25519"]),
    inSubset: () => true,
  },
  {
    name: "import_export/ec_importKey",
    module: "group-ec-import-key.js",
    start: (ns) => ns.run_ec_import_tests(),
    inSubset: ecImportInSubset,
  },
  {
    name: "import_export/ec_importKey_failures (ECDSA)",
    module: "group-ec-import-key-failures.js",
    start: (ns) => ns.run_test(["ECDSA"]),
    inSubset: ecImportFailuresInSubset,
  },
  {
    name: "import_export/rsa_importKey",
    module: "group-rsa-import-key.js",
    start: (ns) => ns.run_rsa_import_tests(),
    inSubset: rsaImportInSubset,
  },
  {
    name: "getRandomValues",
    module: "group-get-random-values.js",
    start: (ns) => ns.run_get_random_values_tests(),
    inSubset: getRandomValuesInSubset,
  },
  {
    name: "randomUUID",
    module: "group-random-uuid.js",
    start: (ns) => ns.run_random_uuid_tests(),
    inSubset: randomUuidInSubset,
  },
  {
    name: "normalize-algorithm-name",
    module: "group-normalize-algorithm-name.js",
    start: (ns) => ns.run_normalize_algorithm_name_tests(),
    inSubset: normalizeAlgorithmNameInSubset,
  },
  {
    name: "crypto_key_cached_slots",
    module: "group-crypto-key-cached-slots.js",
    start: (ns) => ns.run_crypto_key_cached_slots_tests(),
    inSubset: cachedSlotsInSubset,
  },
];
