// The vendored WPT groups and the subset definition, shared by every
// environment that runs them: `runner.js` and `parity-runner.js`
// (componentize-js guests, static imports), `parity/baseline.mjs` (Node,
// dynamic imports), and the browser parity page (`web/`). This module is
// dependency-free — it names each group's suite module instead of importing
// it — so its specifier resolves identically under componentize-js's
// base-directory resolution and ordinary ESM.
//
// Each entry is `{ name, module, start, inSubset }`:
//
//   - `name` keys the group everywhere results are recorded: the census in
//     `expected.js`, the loss ratchet in `parity/losses.js`, and the parity
//     comparator's records.
//   - `module` is the suite module's filename under `build/` (generated by
//     `component.sh suites`); the consumer resolves and imports it.
//   - `start(ns)` registers the group's tests, given that module's
//     namespace. It runs with `harness.js`'s globals installed
//     (`promise_test` and friends).
//   - `inSubset(name)` classifies a test by its WPT name: *in-subset* tests
//     — those whose parameters the webcrypto-componentize library documents
//     as served — must pass under the gating runner; the rest are expected
//     to fail with the library's documented fail-closed errors. These
//     classifiers are the machine-readable definition of "the portion of
//     WPT this library implements"; their doc comments enumerate each
//     group's boundary.

// --- the subset definition, one classifier per group ---------------------------

/**
 * sign_verify/hmac: the served hashes (SHA-1 through the package's
 * `hmac-sha1` interface, and the SHA-2 family); the wrong-algorithm tests
 * need ECDSA generation (class D).
 */
function hmacInSubset(name) {
  if (name === "setup") {
    return true;
  }
  return /SHA-(1|256|384|512)\b/.test(name) && !/wrong algorithm|generate wrong key/.test(name);
}

/**
 * encrypt_decrypt/aes_gcm (96-bit iv): 128- and 256-bit keys at every
 * legal tag length (per-call `tag-size` carries them all), plus the
 * illegal-tag-length rejections and the mismatched-key tests (their
 * AES-CBC fixture is served); AES-192 is declined package-wide.
 */
function gcmInSubset(name) {
  if (name === "setup") {
    return true;
  }
  return /(128|256)-bit key/.test(name);
}

/**
 * encrypt_decrypt/{aes_cbc,aes_ctr}: 128- and 256-bit keys; AES-192 is
 * declined package-wide, and the mismatched-key test needs the *other*
 * unauthenticated mode's fixture to import (it does — both are served —
 * so it is in).
 * @param {string} name
 */
function cipherInSubset(name) {
  return name === "setup" || /(128|256)-bit key/.test(name);
}

/**
 * import_export/symmetric_importKey: the "raw" and "jwk" formats;
 * HMAC-SHA-256 at any key size, the AES family at 128/256 bits.
 * Empty-usages tests are in for any parameters (usages are validated
 * before key material either way).
 */
function importKeyInSubset(name) {
  if (!name.includes("(raw, ") && !name.includes("(jwk, ")) {
    return false;
  }
  if (name.startsWith("Empty Usages:")) {
    return true;
  }
  if (/\{hash: SHA-(1|256|384|512), name: HMAC\}/.test(name)) {
    return true;
  }
  if (/\{name: AES-(GCM|CBC|CTR)\}/.test(name)) {
    return / (128|256) bits /.test(name);
  }
  return false;
}

/**
 * generateKey/successes: HMAC-SHA-256 (default or explicit length) and
 * AES-GCM at 256 bits, extractable or not (extractable cases export raw
 * and JWK), at every legal usage combination (wrap/unwrap usages are key
 * metadata). Algorithm-name case variants are in (names are
 * case-insensitive).
 */
function generateKeyInSubset(name) {
  if (/name: hmac/i.test(name)) {
    return /hash: SHA-(1|256|384|512)\b/.test(name);
  }
  if (/name: aes-(gcm|cbc|ctr)/i.test(name)) {
    return /length: (128|256)/.test(name);
  }
  return false;
}

/**
 * sign_verify/ecdsa: every test needs ECDSA signing or a generated pair —
 * `ecdsa-sign` is class D, withheld by the in-guest provider this shim
 * composes with (see the shim header) — so the subset stays empty and the
 * group meters that gap. The verify path's behavioral assertions live in
 * the conformance suites.
 */
function classDGatedInSubset() {
  return false;
}

/**
 * derive_bits_keys/cfrg_curves_bits (X25519): served except "mismatched
 * algorithms", whose fixture needs an imported ECDH public key (null
 * here, so the failure is the wrong `TypeError`).
 * @param {string} name
 */
function cfrgBitsInSubset(name) {
  return !name.includes("mismatched algorithms");
}

/**
 * import_export/okp_importKey (Ed25519): every served form — raw and spki
 * public, private PKCS#8 and OKP JWKs (public and private).
 */
function okpEd25519ImportInSubset() {
  return true;
}

/**
 * import_export/okp_importKey_failures (Ed25519): every form's rejections
 * are served.
 */
function okpEd25519FailuresInSubset() {
  return true;
}

/**
 * derive_bits_keys/{hkdf,pbkdf2}: the served subset is SHA-256/384/512
 * derivations over importable base secrets, with derived-key targets the
 * WIT's `derive-key` mints span (AES-GCM 256, HMAC-SHA-256).
 *
 * Excluded, in match order: subtests needing an ECDH key (`generateKey`
 * does not serve ECDH, so the fixture is null); the empty HKDF base key
 * (WIT-forced — `import-ikm` rejects empty material by ruling); and
 * unserved derived-key targets. The SHA-1 rows are served (the
 * `hkdf-sha1`/`pbkdf2-sha1` interfaces).
 *
 * The exclusions are whole-row, so the census pins a large `outPassed`
 * for these groups: an unserved-target row's bad-hash and missing-usage
 * subtests often expect the same `DOMException` name the unserved-target
 * refusal carries, and pass for that wrong reason. Claiming a
 * coincidence would let it silently break when the target is served, so
 * they stay out-of-subset, visible in the pinned census.
 * @param {string} name
 */
function kdfDeriveInSubset(name) {
  if (name === "setup - define tests") {
    return true;
  }
  if (name.includes("wrong (ECDH) key")) {
    return false;
  }
  if (name.includes("empty derivedKey")) {
    return false;
  }
  if (name.startsWith("Derived key of type")) {
    const served =
      /^Derived key of type name: AES-(GCM|CBC|CTR) length: (128|256)/.test(name) ||
      /^Derived key of type name: HMAC hash: SHA-(1|256|384|512)\b/.test(name);
    if (!served) {
      return false;
    }
  }
  if (/bad hash name|missing deriveBits usage|missing deriveKey usage/.test(name)) {
    return true;
  }
  return true;
}

/**
 * import_export/ec_importKey: the public ECDSA P-256/P-384 forms are
 * served — raw and spki uncompressed points and public EC JWKs. Out: the
 * compressed-point rows (an optional feature: `assert_implements_optional`
 * is a failure in this two-status harness, and whether the WIT spki
 * import accepts compression is implementation-defined — the composed
 * provider happens to, which the census pins as `outPassed`), the private
 * forms (pkcs8 and JWKs carrying `d` — class D, see the shim header),
 * P-521 (declared by the WIT and served by nothing), and ECDH (not an
 * algorithm here at all).
 * @param {string} name
 */
function ecImportInSubset(name) {
  if (!name.includes("name: ECDSA") || name.includes("P-521") || name.includes("compressed")) {
    return false;
  }
  return !name.includes("(pkcs8") && !name.includes(", d)");
}

/**
 * import_export/ec_importKey_failures (ECDSA): the public-form rejections
 * are served — for P-521 only the usage rejections, whose check precedes
 * the curve's — plus the missing-algorithm-name rows, whose `TypeError`
 * precedes every format and curve consideration. The private forms stay
 * out (class D).
 * @param {string} name
 */
function ecImportFailuresInSubset(name) {
  if (name.startsWith("Missing algorithm name")) {
    return true;
  }
  if (name.includes("(pkcs8") || name.includes("jwk(private)")) {
    return false;
  }
  return name.startsWith("Bad usages") || !name.includes("P-521");
}

/** getRandomValues: the whole group is served. */
function getRandomValuesInSubset() {
  return true;
}

/** randomUUID: the whole group is served. */
function randomUuidInSubset() {
  return true;
}

/**
 * digest/digest: the whole group — the SHA-2 family, the bad-algorithm-name
 * rejections, the missing-name `TypeError`s, and the SHA-1 rows, which the
 * shim serves through the package's `sha1-checked` interface (mitigating
 * posture: byte-identical to the platform on every honest input, which is
 * all WPT hashes).
 */
function digestInSubset() {
  return true;
}

/**
 * import_export/okp_importKey (X25519): every served form — raw and spki
 * public, private PKCS#8 and OKP JWKs (public and private), extractable
 * or not (the gated private exports are served).
 */
function okpImportInSubset() {
  return true;
}

/**
 * import_export/okp_importKey_failures (X25519): every form's rejections
 * are served.
 */
function okpImportFailuresInSubset() {
  return true;
}

// --- the group table --------------------------------------------------------------

export const GROUPS = [
  {
    name: "sign_verify/hmac",
    module: "group-hmac.js",
    start: (ns) => ns.run_test(),
    inSubset: hmacInSubset,
  },
  {
    name: "encrypt_decrypt/aes_gcm (96-bit iv)",
    module: "group-aes-gcm.js",
    start: (ns) => ns.run_test(),
    inSubset: gcmInSubset,
  },
  {
    name: "encrypt_decrypt/aes_cbc",
    module: "group-aes-cbc.js",
    start: (ns) => ns.run_test(),
    inSubset: cipherInSubset,
  },
  {
    name: "encrypt_decrypt/aes_ctr",
    module: "group-aes-ctr.js",
    start: (ns) => ns.run_test(),
    inSubset: cipherInSubset,
  },
  {
    name: "import_export/symmetric_importKey (HMAC, AES-GCM)",
    module: "group-import-key.js",
    start: (ns) => {
      ns.runTests("HMAC");
      ns.runTests("AES-GCM");
    },
    inSubset: importKeyInSubset,
  },
  {
    name: "generateKey/successes (HMAC, AES-GCM)",
    module: "group-generate-key.js",
    start: (ns) => ns.run_test(["HMAC", "AES-GCM"]),
    inSubset: generateKeyInSubset,
  },
  {
    name: "derive_bits_keys/cfrg_curves_bits (X25519)",
    module: "group-cfrg-bits.js",
    start: (ns) => promise_test(ns.define_tests_25519, "setup - define tests"),
    inSubset: cfrgBitsInSubset,
  },
  {
    name: "derive_bits_keys/cfrg_curves_keys (X25519)",
    module: "group-cfrg-keys.js",
    start: (ns) => promise_test(ns.define_tests_25519, "setup - define tests"),
    inSubset: cfrgBitsInSubset,
  },
  {
    name: "import_export/okp_importKey (X25519)",
    module: "group-okp-import-key.js",
    start: (ns) => ns.runTests("X25519"),
    inSubset: okpImportInSubset,
  },
  {
    name: "import_export/okp_importKey_failures (X25519)",
    module: "group-okp-import-key-failures.js",
    start: (ns) => ns.run_test(["X25519"]),
    inSubset: okpImportFailuresInSubset,
  },
  {
    name: "generateKey/successes (X25519)",
    module: "group-generate-key.js",
    start: (ns) => ns.run_test(["X25519"]),
    inSubset: () => true,
  },
  {
    name: "derive_bits_keys/hkdf",
    module: "group-hkdf-derive.js",
    start: (ns) => promise_test(ns.define_tests, "setup - define tests"),
    inSubset: kdfDeriveInSubset,
  },
  {
    name: "derive_bits_keys/pbkdf2",
    module: "group-pbkdf2-derive.js",
    start: (ns) => promise_test(ns.define_tests, "setup - define tests"),
    inSubset: kdfDeriveInSubset,
  },
  {
    name: "digest/digest",
    module: "group-digest.js",
    start: (ns) => ns.run_digest_tests(),
    inSubset: digestInSubset,
  },
  {
    name: "sign_verify/eddsa (Ed25519)",
    module: "group-eddsa.js",
    start: (ns) => ns.run_test("Ed25519"),
    inSubset: () => true,
  },
  {
    name: "sign_verify/eddsa_small_order_points",
    module: "group-eddsa-small-order.js",
    start: (ns) => ns.run_test(),
    inSubset: () => true,
  },
  {
    name: "sign_verify/ecdsa",
    module: "group-ecdsa.js",
    start: (ns) => ns.run_test(),
    inSubset: classDGatedInSubset,
  },
  {
    name: "import_export/okp_importKey (Ed25519)",
    module: "group-okp-import-key.js",
    start: (ns) => ns.runTests("Ed25519"),
    inSubset: okpEd25519ImportInSubset,
  },
  {
    name: "import_export/okp_importKey_failures (Ed25519)",
    module: "group-okp-import-key-failures.js",
    start: (ns) => ns.run_test(["Ed25519"]),
    inSubset: okpEd25519FailuresInSubset,
  },
  {
    name: "generateKey/successes (Ed25519)",
    module: "group-generate-key.js",
    start: (ns) => ns.run_test(["Ed25519"]),
    inSubset: () => true,
  },
  {
    name: "import_export/ec_importKey",
    module: "group-ec-import-key.js",
    start: (ns) => ns.run_ec_import_tests(),
    inSubset: ecImportInSubset,
  },
  {
    name: "import_export/ec_importKey_failures (ECDSA)",
    module: "group-ec-import-key-failures.js",
    start: (ns) => ns.run_test(["ECDSA"]),
    inSubset: ecImportFailuresInSubset,
  },
  {
    name: "getRandomValues",
    module: "group-get-random-values.js",
    start: (ns) => ns.run_get_random_values_tests(),
    inSubset: getRandomValuesInSubset,
  },
  {
    name: "randomUUID",
    module: "group-random-uuid.js",
    start: (ns) => ns.run_random_uuid_tests(),
    inSubset: randomUuidInSubset,
  },
];
