//! Raw `bindgen!` output for the `polymorph:webcrypto` package.
//!
//! The crate implements the full package surface — every interface the
//! `imports` world below names. See [`crate`] for the public API built on
//! top of these bindings.

#[allow(missing_docs, reason = "generated code")]
mod generated {
    wasmtime::component::bindgen!({
        path: "wit",
        world: "imports",
        imports: {
            // The async WIT functions (key minting, `%export`, `sign`,
            // `verify`, `seal`, `open`, and every resource drop)
            // need all three: `async` for the component-model async ABI,
            // `store` for `Accessor` access to the `ResourceTable` (and the
            // `…WithStore` traits that host the async methods), and
            // `trappable` so the host functions can return `wasmtime::Result`
            // and surface host errors as traps.
            default: async | store | trappable,
            // The synchronous WIT functions are bound synchronously (still
            // `trappable`, but not `async`): the algorithm getters only
            // touch the `ResourceTable`, which the sync `Host` traits reach
            // through the `WasiWebcryptoCtxView` data type.
            "polymorph:webcrypto/mac@0.1.0.[method]mac-key.algorithm-name": trappable,
            "polymorph:webcrypto/mac@0.1.0.[method]mac-key.algorithm-hash": trappable,
            "polymorph:webcrypto/mac@0.1.0.[method]mac-key.algorithm-length": trappable,
            "polymorph:webcrypto/mac@0.1.0.[method]mac-key.extractable": trappable,
            "polymorph:webcrypto/mac@0.1.0.[method]mac-key.can-sign": trappable,
            "polymorph:webcrypto/mac@0.1.0.[method]mac-key.can-verify": trappable,
            "polymorph:webcrypto/mac@0.1.0.[constructor]mac-key-options": trappable,
            "polymorph:webcrypto/mac@0.1.0.[method]mac-key-options.can-sign": trappable,
            "polymorph:webcrypto/mac@0.1.0.[method]mac-key-options.can-verify": trappable,
            "polymorph:webcrypto/mac@0.1.0.[method]mac-key-options.extractable": trappable,
            "polymorph:webcrypto/aead@0.1.0.[method]aead-key.algorithm-name": trappable,
            "polymorph:webcrypto/aead@0.1.0.[method]aead-key.algorithm-length": trappable,
            "polymorph:webcrypto/aead@0.1.0.[method]aead-key.nonce-size": trappable,
            "polymorph:webcrypto/aead@0.1.0.[method]aead-key.tag-size": trappable,
            "polymorph:webcrypto/aead@0.1.0.[method]aead-key.extractable": trappable,
            "polymorph:webcrypto/aead@0.1.0.[method]aead-key.can-seal": trappable,
            "polymorph:webcrypto/aead@0.1.0.[method]aead-key.can-open": trappable,
            "polymorph:webcrypto/aead@0.1.0.[method]aead-key.can-wrap": trappable,
            "polymorph:webcrypto/aead@0.1.0.[method]aead-key.can-unwrap": trappable,
            "polymorph:webcrypto/aead@0.1.0.[constructor]aead-key-options": trappable,
            "polymorph:webcrypto/aead@0.1.0.[method]aead-key-options.can-seal": trappable,
            "polymorph:webcrypto/aead@0.1.0.[method]aead-key-options.can-open": trappable,
            "polymorph:webcrypto/aead@0.1.0.[method]aead-key-options.can-wrap": trappable,
            "polymorph:webcrypto/aead@0.1.0.[method]aead-key-options.can-unwrap": trappable,
            "polymorph:webcrypto/aead@0.1.0.[method]aead-key-options.extractable": trappable,
            "polymorph:webcrypto/cipher@0.1.0.[method]cipher-key.algorithm-name": trappable,
            "polymorph:webcrypto/cipher@0.1.0.[method]cipher-key.algorithm-length": trappable,
            "polymorph:webcrypto/cipher@0.1.0.[method]cipher-key.iv-size": trappable,
            "polymorph:webcrypto/cipher@0.1.0.[method]cipher-key.extractable": trappable,
            "polymorph:webcrypto/cipher@0.1.0.[method]cipher-key.can-encrypt": trappable,
            "polymorph:webcrypto/cipher@0.1.0.[method]cipher-key.can-decrypt": trappable,
            "polymorph:webcrypto/cipher@0.1.0.[method]cipher-key.can-wrap": trappable,
            "polymorph:webcrypto/cipher@0.1.0.[method]cipher-key.can-unwrap": trappable,
            "polymorph:webcrypto/cipher@0.1.0.[constructor]cipher-key-options": trappable,
            "polymorph:webcrypto/cipher@0.1.0.[method]cipher-key-options.can-encrypt": trappable,
            "polymorph:webcrypto/cipher@0.1.0.[method]cipher-key-options.can-decrypt": trappable,
            "polymorph:webcrypto/cipher@0.1.0.[method]cipher-key-options.can-wrap": trappable,
            "polymorph:webcrypto/cipher@0.1.0.[method]cipher-key-options.can-unwrap": trappable,
            "polymorph:webcrypto/cipher@0.1.0.[method]cipher-key-options.extractable": trappable,
            "polymorph:webcrypto/derivation@0.1.0.[constructor]derive-options": trappable,
            "polymorph:webcrypto/derivation@0.1.0.[method]derive-options.can-derive-bits": trappable,
            "polymorph:webcrypto/derivation@0.1.0.[method]derive-options.can-derive-key": trappable,
            "polymorph:webcrypto/derivation@0.1.0.[method]derive-input.can-derive-bits": trappable,
            "polymorph:webcrypto/derivation@0.1.0.[method]derive-input.can-derive-key": trappable,
            "polymorph:webcrypto/key-agreement@0.1.0.[constructor]agreement-key-options": trappable,
            "polymorph:webcrypto/key-agreement@0.1.0.[method]agreement-key-options.can-derive-bits": trappable,
            "polymorph:webcrypto/key-agreement@0.1.0.[method]agreement-key-options.can-derive-key": trappable,
            "polymorph:webcrypto/key-agreement@0.1.0.[method]agreement-key-options.extractable": trappable,
            "polymorph:webcrypto/key-agreement@0.1.0.[method]public-key.algorithm-name": trappable,
            "polymorph:webcrypto/key-agreement@0.1.0.[method]secret-key.algorithm-name": trappable,
            "polymorph:webcrypto/key-agreement@0.1.0.[method]secret-key.can-derive-bits": trappable,
            "polymorph:webcrypto/key-agreement@0.1.0.[method]secret-key.can-derive-key": trappable,
            "polymorph:webcrypto/key-agreement@0.1.0.[method]secret-key.extractable": trappable,
            "polymorph:webcrypto/hkdf@0.1.0.[method]ikm.can-derive-bits": trappable,
            "polymorph:webcrypto/hkdf@0.1.0.[method]ikm.can-derive-key": trappable,
            "polymorph:webcrypto/pbkdf2@0.1.0.[method]password.can-derive-bits": trappable,
            "polymorph:webcrypto/pbkdf2@0.1.0.[method]password.can-derive-key": trappable,
            "polymorph:webcrypto/digest@0.1.0.[method]digest.algorithm-name": trappable,
            "polymorph:webcrypto/sha2@0.1.0.make-digest": trappable,
            "polymorph:webcrypto/sha1-checked@0.1.0.make-rejecting-digest": trappable,
            "polymorph:webcrypto/sha1-checked@0.1.0.make-mitigating-digest": trappable,
            "polymorph:webcrypto/signature@0.1.0.[method]verifying-key.algorithm-name": trappable,
            "polymorph:webcrypto/signature@0.1.0.[method]verifying-key.algorithm-curve": trappable,
            "polymorph:webcrypto/signature@0.1.0.[method]verifying-key.algorithm-hash": trappable,
            "polymorph:webcrypto/signature@0.1.0.[method]verifying-key.algorithm-length": trappable,
            "polymorph:webcrypto/signature@0.1.0.[method]verifying-key.algorithm-public-exponent": trappable,
            "polymorph:webcrypto/signature@0.1.0.[method]signing-key.algorithm-name": trappable,
            "polymorph:webcrypto/signature@0.1.0.[method]signing-key.algorithm-curve": trappable,
            "polymorph:webcrypto/signature@0.1.0.[method]signing-key.algorithm-hash": trappable,
            "polymorph:webcrypto/signature@0.1.0.[method]signing-key.algorithm-length": trappable,
            "polymorph:webcrypto/signature@0.1.0.[method]signing-key.algorithm-public-exponent": trappable,
            "polymorph:webcrypto/signature@0.1.0.[method]signing-key.extractable": trappable,
            "polymorph:webcrypto/signature@0.1.0.[method]signing-key.can-sign": trappable,
            "polymorph:webcrypto/signature@0.1.0.[constructor]signing-key-options": trappable,
            "polymorph:webcrypto/signature@0.1.0.[method]signing-key-options.can-sign": trappable,
            "polymorph:webcrypto/signature@0.1.0.[method]signing-key-options.extractable": trappable,
            "polymorph:webcrypto/key-wrap@0.1.0.[method]kw-key.algorithm-name": trappable,
            "polymorph:webcrypto/key-wrap@0.1.0.[method]kw-key.algorithm-length": trappable,
            "polymorph:webcrypto/key-wrap@0.1.0.[method]kw-key.extractable": trappable,
            "polymorph:webcrypto/key-wrap@0.1.0.[method]kw-key.can-wrap": trappable,
            "polymorph:webcrypto/key-wrap@0.1.0.[method]kw-key.can-unwrap": trappable,
            "polymorph:webcrypto/key-wrap@0.1.0.[constructor]kw-key-options": trappable,
            "polymorph:webcrypto/key-wrap@0.1.0.[method]kw-key-options.can-wrap": trappable,
            "polymorph:webcrypto/key-wrap@0.1.0.[method]kw-key-options.can-unwrap": trappable,
            "polymorph:webcrypto/key-wrap@0.1.0.[method]kw-key-options.extractable": trappable,
            "polymorph:webcrypto/public-encryption@0.1.0.[constructor]decryption-key-options": trappable,
            "polymorph:webcrypto/public-encryption@0.1.0.[method]decryption-key-options.can-decrypt": trappable,
            "polymorph:webcrypto/public-encryption@0.1.0.[method]decryption-key-options.can-unwrap": trappable,
            "polymorph:webcrypto/public-encryption@0.1.0.[method]decryption-key-options.extractable": trappable,
            "polymorph:webcrypto/public-encryption@0.1.0.[method]encryption-key.algorithm-name": trappable,
            "polymorph:webcrypto/public-encryption@0.1.0.[method]encryption-key.algorithm-hash": trappable,
            "polymorph:webcrypto/public-encryption@0.1.0.[method]encryption-key.algorithm-length": trappable,
            "polymorph:webcrypto/public-encryption@0.1.0.[method]encryption-key.algorithm-public-exponent": trappable,
            "polymorph:webcrypto/public-encryption@0.1.0.[method]decryption-key.algorithm-name": trappable,
            "polymorph:webcrypto/public-encryption@0.1.0.[method]decryption-key.algorithm-hash": trappable,
            "polymorph:webcrypto/public-encryption@0.1.0.[method]decryption-key.algorithm-length": trappable,
            "polymorph:webcrypto/public-encryption@0.1.0.[method]decryption-key.algorithm-public-exponent": trappable,
            "polymorph:webcrypto/public-encryption@0.1.0.[method]decryption-key.can-decrypt": trappable,
            "polymorph:webcrypto/public-encryption@0.1.0.[method]decryption-key.can-unwrap": trappable,
            "polymorph:webcrypto/public-encryption@0.1.0.[method]decryption-key.extractable": trappable,
        },
        with: {
            "polymorph:webcrypto/mac.mac-key": crate::MacKey,
            "polymorph:webcrypto/mac.mac-key-options": crate::MacKeyOptions,
            "polymorph:webcrypto/derivation.derive-options": crate::DeriveOptions,
            "polymorph:webcrypto/derivation.derive-input": crate::DeriveInput,
            "polymorph:webcrypto/wrapping.wrap-input": crate::WrapInput,
            "polymorph:webcrypto/wrapping.unwrap-input": crate::UnwrapInput,
            "polymorph:webcrypto/key-wrap.kw-key": crate::KwKey,
            "polymorph:webcrypto/key-wrap.kw-key-options": crate::KwKeyOptions,
            "polymorph:webcrypto/hkdf.ikm": crate::Ikm,
            "polymorph:webcrypto/pbkdf2.password": crate::Password,
            "polymorph:webcrypto/key-agreement.agreement-key-options": crate::AgreementKeyOptions,
            "polymorph:webcrypto/key-agreement.public-key": crate::AgreementPublicKey,
            "polymorph:webcrypto/key-agreement.secret-key": crate::AgreementSecretKey,
            "polymorph:webcrypto/aead.aead-key-options": crate::AeadKeyOptions,
            "polymorph:webcrypto/signature.signing-key-options": crate::SigningKeyOptions,
            "polymorph:webcrypto/aead.aead-key": crate::AeadKey,
            "polymorph:webcrypto/cipher.cipher-key": crate::CipherKey,
            "polymorph:webcrypto/cipher.cipher-key-options": crate::CipherKeyOptions,
            "polymorph:webcrypto/digest.digest": crate::Digest,
            "polymorph:webcrypto/signature.verifying-key": crate::VerifyingKey,
            "polymorph:webcrypto/signature.signing-key": crate::SigningKey,
            "polymorph:webcrypto/public-encryption.encryption-key": crate::EncryptionKey,
            "polymorph:webcrypto/public-encryption.decryption-key": crate::DecryptionKey,
            "polymorph:webcrypto/public-encryption.decryption-key-options": crate::DecryptionKeyOptions,
        },
    });
}

pub use self::generated::polymorph::*;
